arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: i18n.dart
output-dir: lib/l10n
untranslated-messages-file: lib/l10n/untranslated/untranslated.json
synthetic-package: false
output-class: I18n