// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfc4cgJjp9YuXS-NflQZUlRtLYB6NQ_iU',
    appId: '1:249508352854:web:9d398444d360f7548a3cf7',
    messagingSenderId: '249508352854',
    projectId: 'wallet-a72b4',
    authDomain: 'wallet-a72b4.firebaseapp.com',
    storageBucket: 'wallet-a72b4.appspot.com',
    measurementId: 'G-HM2KLF7V96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdqtxt_2CS7z9oaxagdV-nmujVIQ5l6sk',
    appId: '1:249508352854:android:a6536c0b2f7515158a3cf7',
    messagingSenderId: '249508352854',
    projectId: 'wallet-a72b4',
    storageBucket: 'wallet-a72b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvsKjJNbAn5x08NoRjUhyatVeCiRvpWHo',
    appId: '1:249508352854:ios:3293ef992848b2d98a3cf7',
    messagingSenderId: '249508352854',
    projectId: 'wallet-a72b4',
    storageBucket: 'wallet-a72b4.appspot.com',
    iosClientId:
        '249508352854-juencd2901oqgttghl67k7rr67f79i8n.apps.googleusercontent.com',
    iosBundleId: 'dev.kaio.wallet',
  );
}
